---
title: "Exploratory Analysis"
output: html_document
---

## Project title

Give your project a concise, interesting title that summarizes the entirety of your project

### Authors

Names of your team members

### Date

Winter 2022

### Abstract

No more than three sentences that summarize your project. Focus on the very most important aspects. For example: (1) "Our main question is .... This question is important because .... To address the question, we will ...." (2) "We are concerned with ..., because .... To address this concern, we plan to ...." (3) "Consider that .... This is important because .... Accordingly, we plan to ...."

### Keywords

3-5 keywords that summarize your project.
(e.g., "Keywords: human physiology; bicycle exercise; Gen Z; times-series data")

### Introduction  

Briefly introduce your project.  Include 3-5 research questions. What motivates the questions? Why are they important? (at least 200 words)

### Related Work  

Describe your topic and related work in this space. You must include 3 citations to related work (URLs to similar work, high quality articles from the popular press, research papers, etc. ) Please use a standard citation style of your choice. (at least 200 words)

### The Dataset

Where did you find the data? Please include a link to the data source  
Who collected the data?  
How was the data collected or generated?  
Why was the data collected?  
How many observations (rows) are in your data?  
How many features (columns) are in the data?  
What, if any, ethical questions or questions of power do you need to consider when working with this data?  
What are possible limitations or problems with this data?   (at least 200 words)

### Implications

Assuming you answer your research questions, briefly describe the expected or possible implications for technologists, designers, and policymakers. (at least 150 words)

Our research questions all aim to find answers about how race and involvement in with the criminal justice system affect education for high schoolers in Washington State. Because we are diving into the concept of race and education, this could have very controversial implications for policymakers in Washington, as education is a very important part in the upbringing of the next generation of minds that will be running our country one day. If it is found that race is a factor in the detriment of young people's high school education experiences, and with that a direct connection to their involvement with the criminal justice system, this will prove to be a major flaw in our education and reform systems within Washington State. We will seek to find these answers in all ways that they factor into someone's high school education, whether it be due to discrimination, lack of opportunity, school funding, or any other relevant factors that may contribute to an educational experience.

### Limitations & Challenges
What challenges or limitations might you need to address with your project idea more broadly? Briefly discuss. (at least 150 words)

Our research questions all aim to find answers about how race and involvement in with the criminal justice system affect education for high schoolers in Washington State. Because we are diving into the concept of race and education, this could have very controversial implications for policymakers in Washington, as education is a very important part in the upbringing of the next generation of minds that will be running our country one day. If it is found that race is a factor in the detriment of young people's high school education experiences, and with that a direct connection to their involvement with the criminal justice system, this will prove to be a major flaw in our education and reform systems within Washington State. We will seek to find these answers in all ways that they factor into someone's high school education, whether it be due to discrimination, lack of opportunity, school funding, or any other relevant factors that may contribute to an educational experience.



### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

There are a handful of different challenges and limitations that we will need to address in our research in order to come to a reliable conclusion. The first that comes to mind is the areas in which we choose to target within Washington state. Because school districts are usually controlled by the city or county that they reside in, it will be important to note any distinctions within these separate areas in order to identify any biases. This also applies to any data that we come across when conducting research about involvement with the criminal justice system and its effect on young people's education outcomes. This could pose a challenge as the extra data that we are looking for may not be readily available in the way that we need it, forcing us to adapt based on the information that we know to be true. It is possible that educated inferences will need to be made for the sake of answering our research questions which could limit our findings. However, these are all challenges that can be addressed and should not keep us from answering our questions about the effects race and criminal justice involvement have on young people's education outcomes in Washington State High Schools.

### Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

### Chart 1

Include a chart

Describe why you chose this chart and what information it reveals

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
```

### Chart 2

Include a chart

Describe why you chose this chart and what information it reveals

### Chart 3

Include a chart

Describe why you chose this chart and what information it reveals
